config: {}

## External URL at which AlertManager will be reachable
##
externalUrl: ""

## AlertManager container image
##
image:
  repository: quay.io/prometheus/alertmanager
  tag: v0.5.1

ingress:
    ## If true, AlertManager Ingress will be created
    ##
    enabled: false

    ## Annotations for AlertManager Ingress
    ##
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    fqdn: ""

    ## TLS configuration for AlertManager Ingress
    ## Secret must be manually created in the namespace
    ##
    tls: []
      # - secretName: alertmanager-general-tls
      #   hosts:
      #     - alertmanager.example.com

## Node labels for AlertManager pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## If true, the Operator won't process any AlertManager configuration changes
##
paused: false

## Number of AlertManager replicas desired
##
replicaCount: 1

## Resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # requests:
  #   memory: 400Mi

service:
  ## Annotations to be added to the Service
  ##
  annotations: {}

  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  ## Port to expose on each node
  ## Only used if service.type is 'NodePort'
  ##
  nodePort: 30903

  ## Service type
  ##
  type: ClusterIP

## AlertManager StorageSpec for persistent data
## Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/prometheus.md#storagespec
##
storageSpec: {}
#   class: default
#   resources:
#     requests:
#       storage: 2Gi
#   selector: {}
