apiVersion: v1
description: Manifests, dashboards, and alerting rules for end-to-end Kubernetes cluster monitoring.
engine: gotpl
home: https://github.com/coreos/kube-prometheus
maintainers:
  - name: Michael Goodness
    email: mgoodness@gmail.com
name: kube-prometheus
version: 0.1.0
