{{- $root := . -}}
{{- range .Values.prometheus.ingress }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version }}
    component: prometheus
    heritage: {{ $root.Release.Service }}
    prometheus: "{{ $root.Values.prometheus.name }}"
    release: {{ $root.Release.Name }}
  name: {{ template "fullname" $root }}-prometheus-{{ .name }}
spec:
  rules:
  {{- range .hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus-{{ $root.Values.prometheus.name }}
              servicePort: 9090
  {{- end }}
{{- if .tls }}
  tls:
{{ toYaml .tls | indent 4 }}
{{- end }}
{{- end }}
