# Default values for kube-lego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jetstack/kube-lego
  tag: 0.1.3
  pullPolicy: IfNotPresent
lego:
  email: "ops@example.com"
  prod: false
pod:
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

