apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: "LOG_LEVEL"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: log.level
        - name: "REDIS_HOST"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: redis.host
        - name: "REDIS_PORT"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: redis.port
        - name: "REDIS_DATABASE"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: redis.database
        - name: "LOADER"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: app.loader
        - name: "STORE"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: app.store
        - name: "TIMEOUT"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: app.timeout
        - name: "SENTRY_URL"
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: sentry.url
        resources:
{{ toYaml .Values.resources | indent 12 }}
