# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

DNS:
  Hostname: ""
  TTL: "300"
  Type: "CNAME"

Github:
  OAuth:
    ClientID: ""
    ClientSecret: ""
  Organization: ""
  Admins:
  #  - goruha
  #  - osterman

Master:
  Name: jenkins-master
  Image: "cloudposse/jenkins"
  ImageTag: "latest"
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  AdminUser: admin
  # AdminPassword: <defaults to random>
  Cpu: "200m"
  Memory: "256Mi"
  # Set min/max heap here if needed with:
  # JavaOpts: "-Xms512m -Xmx512m"
  ServicePort: 8080
  ServiceType: ClusterIP
  ContainerPort: 8080
  SlaveListenerPort: 50000

Agent:
  Image: cloudposse/jenkins-slave
  ImageTag: latest
  ImagePullPolicy: "Always"
  Cpu: "200m"
  Memory: "256Mi"

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 8Gi
