dependencies:
  - name: alertmanager
    version: 0.1.0
    repository: http://charts.opsgoodness.com
  - name: prometheus
    version: 0.1.0
    repository: http://charts.opsgoodness.com
  - name: grafana
    version: 0.2.5
    repository: https://kubernetes-charts.storage.googleapis.com
