{{- $root := . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $serviceName := include "common.labels.standard" . -}}
{{- range .Values.ingress }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{- with .labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{ include "common.labels.standard" $root | indent 4 }}
    ingressName: {{ .name }}
  name: {{ include "common.fullname" $root }}-{{ .name }}
spec:
  rules:
{{- range $host, $path := .hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end -}}
{{- with .tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end -}}
{{- end -}}
