apiVersion: v1
name: grafana
version: 0.2.6
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: Ming Hsieh
    email: zanhsieh@gmail.com
  - name: Cloud Posse LLC
    email: hello@cloudposse.com
engine: gotpl
